server:
  port: ${SERVER_PORT:37002}

spring:
  application:
    name: cloud-feign-consumer-service
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${MYSQL_HOST:192.168.104.141}:${MYSQL_PORT:3306}/${MYSQL_DB:ai_kg_data_upgrade}?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:ai_kg}
    password: ENC(${MYSQL_PASSWORD:8ec942c3e70a489314c31229cbc5bf858748049a03257d4bf03e4f3860023b38c40a7517a4d6a0360ffdeea04fc0e423})
  jackson:
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/**/**/**Mapper.xml
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
      table-prefix: aikg_
  configuration:
    # 是否开启自动驼峰命名
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # sql打印
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 设置feign超时时间
# default为全局配置，如果要单独配置每个服务，改为服务名
feign:
  client:
    config:
      default:
        connect-timeout: 10000  # 指的是建立连接后从服务器读取到可用资源所用的时间。
        read-timeout: 60000     # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  circuitbreaker:
    enabled: true
  hystrix:
    enabled: true

